"""
This type stub file was generated by pyright.
"""

class Spin:
    def __init__(self, parent_widget, interval=..., step=..., autostart=...) -> None:
        ...

    def setup(self, icon_painter, painter, rect): # -> None:
        ...

    def start(self): # -> None:
        ...

    def stop(self): # -> None:
        ...



class Pulse(Spin):
    def __init__(self, parent_widget, autostart=...) -> None:
        ...



