"""
This type stub file was generated by pyright.
"""

from qtpy import QtCore, QtWidgets

DEFAULT_VIEW_COLUMNS = ...
VIEW_COLUMNS_OPTIONS = ...
AUTO_SEARCH_TIMEOUT = ...
ALL_COLLECTIONS = ...
class IconBrowser(QtWidgets.QMainWindow):
    """
    A small browser window that allows the user to search through all icons from
    the available version of QtAwesome.  You can also copy the name and python
    code for the currently selected icon.
    """
    def __init__(self) -> None:
        ...



class IconListView(QtWidgets.QListView):
    """
    A QListView that scales it's grid size to ensure the same number of
    columns are always drawn.
    """
    def __init__(self, columns, parent=...) -> None:
        ...

    def setColumns(self, cols): # -> None:
        """
        Set columns number and resize.
        """
        ...

    def resizeEvent(self, event): # -> None:
        """
        Re-implemented to resize view following number of columns available.
        """
        ...



class IconModel(QtCore.QStringListModel):
    def __init__(self) -> None:
        ...

    def flags(self, index):
        ...

    def data(self, index, role): # -> QIcon | Any:
        """
        Re-implemented to return the icon for the current index.

        Parameters
        ----------
        index : QtCore.QModelIndex
        role : int

        Returns
        -------
        Any
        """
        ...



def run():
    """
    Start the IconBrowser and block until the process exits.
    """
    ...

if __name__ == '__main__':
    ...
